Meson build system + Fixes
AlonsoEnrique/Quotes pull request #17
Opened 2019-04-02 10:48 UTC by NathanBnm

Hi! Everything seems to build fine but someone more familiar with meson and elementary development should take a look at this.

I'm not sure about the Debian package, you'll have to check that.

This PR will resolves #13 #14 #15.

# Changelog
- Switch from cmake to meson
- Remove Google+ (See #15)
- Add translations (See #14)
- Add translations for `desktop` and `appdata` files too (in the `po\extra` directory)
- Add French translations
- Update OARS data (See #13)

2019-04-02 19:25 UTC, AlonsoEnrique commented
@cassidyjames any chance for review this? Thanks

2019-04-02 20:14 UTC, NathanBnm commented
EDIT : I just removed some deprecated attributes. But I don't know if "CSS_URL" attribute is deprecated or not. In doubt I left it for now.

I noticed too that the social icons (now Facebook and Twitter) are a little bigger than before. Maybe you'll have to check that.

Finally I didn't implemented the `tests` folder 'cause I don't know how. (It's make me think that I forgot to remove the deprecated attributes in the test file).

2019-06-08 10:33 UTC, NathanBnm commented
@malonso11 I removed some deprecated attributes and outdated tests :smile: 
All should be good now, there is still the issue I mentioned before with social icons size.

@ryonakano any chance to review this please? :smile:

2019-06-08 11:51 UTC, ryonakano requested changes
I am happy because you regard me as worth reviewing this PR. :tada: 

However, there are some points I would like to say:

### Keep Your PRs as Simple as Possible

As I said before, keep you PRs as simple as possible. I think this PR contains so many and different changes. I think we can separate this PR to some PRs like:

* Switch to meson (this also include README.md changes because it contains how to build. Updating debian packaging, too)
* Remove Google+ icons and links
* Make more strings translatable
* Updating translation files
* Add French translation
* Update copyright header
* Use UpperCamelCase for filenames
* Add Travis CI (but in usual this should be done by repository owner. I'll mention later)

If contributors create simple PRs it will make both repository owners and contributors happy. For owners simple PRs are easy to understand what contributors want to change, and easy to review because changes should be a few and reviewing does not take so much time. For contributors if a repository owner requests changes, what they need to address changes should not so many.
Another good point simple PR has is that If a PR is need to be reverted after merged the effects by reverting are less.

### Don't Add Travis CI

You've added `.travis.yml`. However, just adding this file is not enough: we need to log in travis-ci.org and enable CI check for the repository in the dashboard. Actually other than a repository owner can't do this. So I don't think you need to add this file. What you can do is, for example, urge a repository owner to add CI checks by submitting Issue.

Although I looked over your PR, there might be some points I forgot to request changes. So I'm going to review your PR again after you address the following points I mentioned. Thank you for your work :+1:

2019-06-08 11:51 UTC, ryonakano commented on README.md
> +Please make sure you have these dependencies first before building:
I don't mean to nitpick, but I personally prefer following how elementary write, since this app is mainly designed for elementary OS: see https://github.com/elementary/calendar#building-and-installation for example.

So it will be like this:

```markdown
## Building and Installation

You'll need the following dependencies:

* libgranite-dev
* libgtk-3-dev
* libjson-glib-dev
* libsoup2.4-dev
* meson
* valac

Run `meson build` to configure the build environment. Change to the build directory and run `ninja` to build

    meson build --prefix=/usr
    cd build
    ninja

To install, use `ninja install`, then execute with `com.github.alonsoenrique.quotes`

    sudo ninja install
    com.github.alonsoenrique.quotes
```

2019-06-08 11:51 UTC, ryonakano commented on README.md
> +meson build && cd build
This is also a tiny thing, but elementary developers seem to prefer to use 4 spaces instead of using "\`\`\`bash" to show commands

2019-06-08 11:51 UTC, ryonakano commented on README.md
> +meson configure --prefix=/usr
```suggestion
meson build --prefix=/usr
```

Also, after running this command, you have to *cd* to `build/` directory.

2019-06-08 11:51 UTC, ryonakano commented on data/com.github.alonsoenrique.quotes.appdata.xml.in
> +        <release version="0.6.0" date="2018-04-30">
I think you don't have to edit release notes. I suppose a repository owner may need to create a new release as soon as the PR is merged if contributors edit them.

2019-06-08 11:51 UTC, ryonakano commented on meson.build
> +project('com.github.alonsoenrique.quotes','vala', 'c', version: '0.6.0')
```suggestion
project('com.github.alonsoenrique.quotes', 'vala', 'c', version: '0.6.0')
```

2019-06-08 11:51 UTC, ryonakano commented on src/Configs/Constants.vala
> +        public abstract const string ID = "com.github.alonsoenrique.quotes";
As far as I searched this constant is only used at line 32 of `Application.vala`. Also, the above constant `PROGRAME_NAME` does not seem to be used in any code. So I think you can hardcode `com.github.alonsoenrique.quotes` and remove this file itself.

2019-06-08 12:33 UTC, ryonakano commented
![Screenshot from 2019-06-08 21-31-37](https://user-images.githubusercontent.com/26003928/59147307-dd76e580-8a34-11e9-9071-a05da465cc8a.png)

This is also a tiny thing, but please make sure you don't remove the last new line of files, otherwise a warning like this will be shown in GitHub diff.

2019-06-08 16:39 UTC, malonso11 commented
Thanks @ryonakano

2019-06-08 20:29 UTC, NathanBnm commented
> I am happy because you regard me as worth reviewing this PR.

Sure I think you make it right that's why I asked you :smile: You're very clear in your explanations. Thanks for giving your time.

> However, there are some points I would like to say:
> ### Keep Your PRs as Simple as Possible
> 
> As I said before, keep you PRs as simple as possible. I think this PR contains so many and different changes.

Sure! You already said me that :laughing: I'm considering it, actually I made this PR before I get your advice last time that's why this one is messy too! 

For everything else you're completely right :wink: I'll take a look to your review when I'll have time and I will make different PR to fix this.

@malonso11 stay tuned but please let me fix this in different PR before merging anything ^^

2019-06-19 14:44 UTC, closed without merging